---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # LMEvalJob CRs (operator will create Jobs + PVCs)
  - lmevaljob-quantized.yaml
  - lmevaljob-full.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: trustyai-evaluation

namespace: private-ai-demo

