apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: stage00-operators
      app.kubernetes.io/part-of: stage00-ai-platform

resources:
# Namespaces
- namespace-openshift-nfd.yaml
- namespace-nvidia-gpu-operator.yaml
- namespace-redhat-ods-operator.yaml

# OperatorGroups
- operatorgroup-nfd.yaml
- operatorgroup-gpu.yaml
- operatorgroup-rhods.yaml

# Subscriptions
- subscription-nfd.yaml
- subscription-gpu-operator-certified.yaml
- subscription-rhods-operator.yaml
- subscription-servicemeshoperator.yaml
- subscription-serverless-operator.yaml
- subscription-openshift-pipelines-operator.yaml
- subscription-authorino-operator.yaml

# TektonConfig (pruner)
- tektonconfig.yaml

