apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  namespace: openshift-operators
  labels:
    app.kubernetes.io/part-of: stage00-ai-platform
    app.kubernetes.io/component: tekton
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  pruner:
    keep: 5
    resources:
      - pipelinerun
      - taskrun
    schedule: "0 2 * * *"

