apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

metadata:
  name: model-registry
  annotations:
    config.kubernetes.io/local-config: "true"

# Model Registration Component
#
# Uses REST API to register models in Model Registry
# Runs once during initial deployment

resources:
  - job-register-models-curl.yaml
