apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: workbench

resources:
  # RBAC
  - serviceaccount.yaml
  - rolebinding.yaml
  
  # Storage
  - pvc.yaml
  
  # Notebooks as ConfigMaps
  - notebook-01-stage1.yaml
  - notebook-02-redhat.yaml
  - notebook-03-eu-ai-act.yaml
  - notebook-04-acme.yaml
  - notebook-05-stage3.yaml
  
  # Workbench
  - notebook.yaml

labels:
  - pairs:
      app.kubernetes.io/component: workbench
      app.kubernetes.io/part-of: llama-stack
