apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Note: PipelineRuns are not included in resources
# They use generateName and should be created imperatively via deploy.sh
# This kustomization file exists for structural consistency

resources: []

commonLabels:
  app.kubernetes.io/instance: stage01-pipelineruns
  app.kubernetes.io/managed-by: argocd

