apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: stage00-datasciencecluster
  app.kubernetes.io/part-of: stage00-ai-platform

resources:
- namespace-istio-system.yaml
- servicemeshcontrolplane.yaml
- datasciencecluster.yaml

