---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhoai-model-registries

resources:
  - mysql-pvc.yaml
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - job-fix-mysql-auth.yaml

labels:
  - pairs:
      app.kubernetes.io/name: model-registry-mysql
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: model-registry

