---
apiVersion: v1
kind: ConfigMap
metadata:
  name: private-ai-registry-db-parameters
  namespace: rhoai-model-registries
  labels:
    app.kubernetes.io/name: model-registry-mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: model-registry
data:
  MYSQL_DATABASE: metadb
  MYSQL_PORT: "3306"
  MYSQL_ALLOW_EMPTY_PASSWORD: "false"

