---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - lmeval-metrics-configmap.yaml
  - lmeval-metrics-serviceaccount.yaml
  - lmeval-metrics-role.yaml
  - lmeval-metrics-rolebinding.yaml
  - lmeval-metrics-cronjob.yaml

commonLabels:
  app.kubernetes.io/name: lmeval-metrics-exporter
  app.kubernetes.io/part-of: private-ai-demo
  stage: "03"


