---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhoai-model-registries

resources:
  - namespace.yaml
  - pvc.yaml
  # secret.yaml is created by deploy.sh (not in Git for security)
  - configmap.yaml
  - deployment.yaml
  - service.yaml

