apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: private-ai-demo

resources:
  # Pipeline ServiceAccount and RBAC
  - serviceaccount-pipeline.yaml
  - role-pipeline.yaml
  - rolebinding-pipeline.yaml
  
  # Build ServiceAccount and RBAC (for privileged Buildah builds)
  - serviceaccount-build.yaml

commonLabels:
  argocd.argoproj.io/instance: stage01-model-serving
  app.kubernetes.io/instance: stage01-pipelines
  app.kubernetes.io/managed-by: argocd

