---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - guardrails-configmap.yaml
  - guardrails-orchestrator.yaml
  - guardrails-route.yaml
  - hf-detector-imagestream.yaml
  - hf-detector-buildconfig.yaml
  - hf-detector-deployment.yaml
  - hf-detector-service.yaml
patches:
  - target:
      kind: Deployment
      name: llama-guardrails
    path: patch-llama-guardrails-env.yaml

commonLabels:
  app.kubernetes.io/name: guardrails-orchestrator
  app.kubernetes.io/part-of: private-ai-demo
  stage: "02"


