---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: worker-gpu
  labels:
    machineconfiguration.openshift.io/role: worker-gpu
    pools.operator.machineconfiguration.openshift.io/worker-gpu: ""
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker
          - worker-gpu
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-gpu: ""
  paused: false
  maxUnavailable: 1

