---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - trustyai-service.yaml
  - trustyai-servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: trustyai-service
  app.kubernetes.io/part-of: private-ai-demo
  stage: "03"


