---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appproject-stage01.yaml
  # Future stages will be added here:
  # - appproject-stage02.yaml
  # - appproject-stage03.yaml
  # - appproject-stage04.yaml

