---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appproject-stage01.yaml
  - appproject-stage02-model-alignment.yaml
  - appproject-stage03-model-monitoring.yaml
  - appproject-stage04-model-integration.yaml

