apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount-model-build.yaml

commonLabels:
  app.kubernetes.io/instance: stage01-pipelines
  app.kubernetes.io/managed-by: argocd
  argocd.argoproj.io/instance: stage01-model-serving

