apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mistral-permissive
  namespace: private-ai-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mistral-24b-quantized
  mtls:
    mode: PERMISSIVE

