apiVersion: v1
kind: Service
metadata:
  name: acme-agent
  namespace: acme-calibration-ops
  labels:
    app: acme-agent
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: acme-agent
  type: ClusterIP

