apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- subscription-nfd.yaml
- subscription-gpu.yaml
- subscription-rhoai.yaml
- subscription-servicemesh.yaml
- subscription-serverless.yaml

