apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: private-ai-demo

resources:
  - imagestreams.yaml
  - buildconfig-database-mcp.yaml
  - buildconfig-slack-mcp.yaml

commonLabels:
  app.kubernetes.io/managed-by: gitops
  app.kubernetes.io/part-of: mcp-servers
