apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-plugin-nvidia-gpu
  namespace: nvidia-gpu-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: console-plugin-nvidia-gpu
  template:
    metadata:
      labels:
        app.kubernetes.io/name: console-plugin-nvidia-gpu
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: console-plugin-nvidia-gpu
          image: quay.io/edge-infrastructure/console-plugin-nvidia-gpu:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9443
              name: https
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/serving-cert
              name: plugin-serving-cert
              readOnly: true
            - mountPath: /opt/app-root/src/plugin-manifest.json
              name: plugin-manifest
              readOnly: true
              subPath: plugin-manifest.json
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
        - name: plugin-manifest
          configMap:
            name: console-plugin-nvidia-manifest

