apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: console-plugin-nvidia-gpu
  app.kubernetes.io/managed-by: gitops
  app.kubernetes.io/part-of: observability

resources:
  - consoleplugin.yaml
  - deployment.yaml
  - service.yaml
  - configmap-metrics.yaml
  - console-enable.yaml

