apiVersion: v1
kind: Service
metadata:
  name: console-plugin-nvidia-gpu
  namespace: nvidia-gpu-operator
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
spec:
  selector:
    app.kubernetes.io/name: console-plugin-nvidia-gpu
  ports:
    - name: https
      port: 9443
      protocol: TCP
      targetPort: 9443

