apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc-pipeline-workspace.yaml

commonLabels:
  app.kubernetes.io/instance: stage01-workspaces
  app.kubernetes.io/managed-by: argocd

