apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - imagestream-mistral-quantized.yaml
  - imagestream-mistral-full.yaml

labels:
  - includeSelectors: true
    pairs:
      argocd.argoproj.io/instance: stage01-model-serving
      app.kubernetes.io/instance: stage01-imagestreams
      app.kubernetes.io/managed-by: argocd

