apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # v3 pipeline (production: multi-task with isolated memory, 4h+ timeouts)
  - pipeline-modelcar-v3.yaml
  
  # Testing pipeline (separate use case)
  - pipeline-model-testing.yaml

labels:
  - includeSelectors: true
    pairs:
      argocd.argoproj.io/instance: stage01-model-serving
      app.kubernetes.io/instance: stage01-pipelines
      app.kubernetes.io/managed-by: argocd

