apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pipeline-model-deployment.yaml

commonLabels:
  app.kubernetes.io/instance: stage01-pipelines
  app.kubernetes.io/managed-by: argocd

