apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Model Import Tasks
  - task-download-model.yaml
  - task-upload-to-minio.yaml
  - task-build-runtime.yaml
  - task-register-model.yaml
  
  # Model Testing Tasks (v2)
  - task-run-lm-eval-v2.yaml
  - task-run-guidellm-v2.yaml
  - task-publish-test-results-v2.yaml

labels:
  - includeSelectors: true
    pairs:
      argocd.argoproj.io/instance: stage01-model-serving
      app.kubernetes.io/instance: stage01-pipelines
      app.kubernetes.io/managed-by: argocd
      pipeline-pattern: minio-first

